# site
title: Maximo Ospital
baseurl: "/"
url: "http://maximoospital.github.io"
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1
logo: "/assets/images/logo.svg"

# bio
header: Maximo Ospital
desc: |+
  hi! welcome to my website!! <br>
  i'm a 21 year old argentinian programming student <br>
  i am also an amateur design and video editing afficionado. <br>
  really interested in both webapp and videogame development. <br>
  big fan of old-looking uis, in case you couldn't tell.

# posts
date_format: "%Y"
post_title: Projects
post_date: Year
post_cat: Type

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock